# jwt configuration
jwt:
  signing-key: 'UltraMan'
  expires-time: 604800
  buffer-time: 86400

# mysql connect configuration
mysql:
  path: '192.168.0.104:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'blog'
  username: 'root'
  password: 'root'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

## redis configuration
#redis:
#  db: 0
#  addr: '127.0.0.1:6379'
#  password: ''

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8000
  db-type: 'mysql'
  oss-type: 'local'
