# mysql connect configuration
mysql:
  path: '192.168.0.104:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'blog'
  username: 'root'
  password: 'root'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8000
  db-type: 'mysql'
  oss-type: 'local'
