# mysql connect configuration
mysql:
  path: '192.168.1.9:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'blog'
  username: 'root'
  password: 'root'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false